spring.application.name=RESTory
spring.data.mongodb.database=restory
spring.data.mongodb.uri=mongodb://localhost:27017,localhost:27018,localhost:27019/restory?replicaSet=rs0&w=majority&readPreference=nearest

# Redis Multi-Node Configuration (Master + Repliche su WSL)
spring.data.redis.nodes=127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0